import type { Metadata } from "next";
import Layout from "./layout.client";
import "./globals.css";

export const metadata: Metadata = {
  title: "RepoFinder - Find Repos",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Layout>
        {children}
      </Layout>
    </html>
  );
}
